### PR TITLE
Including Muon Isolation

### PR DESCRIPTION
**Pull request by yjeong**
I have a fixed a sentence space.

### CODE REVIEW

**Comment by yjeong** [comment]
line 181,182

**Comment by yjeong** [comment]
fixed line 201,202

**Comment by yjeong** [comment]
re fixed

**Comment by yjeong** [comment]
fixed line again Isolation line 201, 202

**Comment by yjeong** [comment]
fixed line using git checkout line 201,202

**Comment by jshlee** [comment]
only have ur additions only

**Comment by yjeong** [comment]
recover line.

**Comment by jshlee** [comment]
getting there

**Comment by jshlee** [comment]
currently this code does nothing

**Comment by yjeong** [comment]
changed directory in ConfFile.cfg

**Comment by jshlee** [comment]
good your getting close

add in Tracker-based relative isolation too
mu->isolationR03().sumPt/mu->pt()

**Comment by yjeong** [comment]
Add in tree of PFIsolationR03, and R04.

**Comment by jshlee** [comment]
ur calculation of isolation is wrong

**Comment by yjeong** [comment]
Add a genMuon Isolation as manual calculation code.
but pfIsolation caculation will fixed it.

**Comment by jshlee** [comment]
i told u what needs fixing

**Comment by jshlee** [comment]
genMuon Isolation isnt needed like this

**Comment by yjeong** [comment]
fix a Muon Isolation.

**Comment by yjeong** [comment]
I have fixed pfIsolation with include track base Isolation.

**Comment by yjeong** [comment]
Include Muon Isolation.

**Comment by jshlee** [comment]
do this
b_recoMuon_TrkIso04 = mu->isolationR04().sumPt/mu->pt();
b_recoMuon_PFIso04 = (mu->pfIsolationR04().sumChargedHadronPt + TMath::Max(0.,mu->pfIsolationR04().sumNeutralHadronEt + mu->pfIsolationR04().sumPhotonEt - 0.5*mu->pfIsolationR04().sumPUPt))/mu->pt();

do the same for R03
and do the same for b_genMuon

**Comment by yjeong** [comment]
Recover and Including Trackbase, PFIsolation.

**Pull request merged**
